version: "3.9"

services:
  web:
    build: .
    command: gunicorn config.wsgi -b 0.0.0.0:8000 #python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-f9!a#_egbhrh0e@4jcl!a9d)&nur0(r4h2^@jf-^!gy5ed+@2("
      - "DJANGO_DEBUG=True"
      - "AWS_ACCESS_KEY_ID=AKIARV5TNXFWDMHBJ2V7"
      - "AWS_SECRET_ACCESS_KEY=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"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"
        
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
