# Generated by Django 3.2.8 on 2021-10-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_squashed_0008_auto_20211010_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.CharField(default='django-htmx', max_length=50),
        ),
    ]
