# Generated by Django 3.2.8 on 2021-10-22 16:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('pages', '0002_alter_blog_tag'), ('pages', '0003_subscribermessage'), ('pages', '0004_blog_draft'), ('pages', '0005_auto_20211021_1348'), ('pages', '0006_alter_project_icon'), ('pages', '0007_alter_project_icon'), ('pages', '0008_alter_project_icon'), ('pages', '0009_project_number'), ('pages', '0010_remove_project_icon'), ('pages', '0011_auto_20211021_1817'), ('pages', '0012_auto_20211021_1846'), ('pages', '0013_auto_20211021_1921'), ('pages', '0014_auto_20211022_1606')]

    dependencies = [
        ('pages', '0001_squashed_0008_auto_20211010_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.CharField(default='django-htmx', max_length=50),
        ),
        migrations.CreateModel(
            name='SubscriberMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='notes',
        ),
        migrations.AddField(
            model_name='blog',
            name='course',
            field=models.BooleanField(default=False),
        ),
    ]
