# Generated by Django 3.2.8 on 2021-10-05 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_blog_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='views',
            new_name='blog_views',
        ),
    ]
