# Generated by Django 3.2.8 on 2021-10-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20211021_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
