# Generated by Django 3.2.8 on 2021-10-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_views_blog_blog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.CharField(default='django/htmx', max_length=50),
        ),
    ]
