# Generated by Django 3.2.8 on 2021-10-10 01:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_blog_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='notes',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
