# Generated by Django 3.2.8 on 2021-10-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_project_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
