# Generated by Django 3.2.8 on 2021-10-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_project_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
