# Generated by Django 3.2.8 on 2021-10-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_project_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='icon',
        ),
    ]
