# Generated by Django 3.2.8 on 2021-10-21 19:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20211021_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='chapter',
        ),
        migrations.AddField(
            model_name='project',
            name='sections',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sidebar',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
