# Generated by Django 3.2.8 on 2021-10-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20211021_1921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='notes',
        ),
        migrations.AddField(
            model_name='blog',
            name='course',
            field=models.BooleanField(default=False),
        ),
    ]
